### ISSUE TITLE
Cannot build udp connection with sitl!

### ISSUE THREAD

**Issue by bidai541** [PX4/jMAVSim#10]
In my machine, jmavsim cannot build udp connection with sitl, how to solve this problem?  The sitl always stays in "waiting for initial data on UDP"!  I have tried sending a UDP message in the terminal, sitl can receive it.

Besides, in sitl mode, jmavsim indicate "/dev/ttyACM0" port not found. My OS is ubuntu14.04.
Thanks very much.

**Comment by bidai541** [comment]
I have solved the problem!

**Comment by LorenzMeier** [comment]
How did you solve it?

**Comment by bidai541** [comment]
I clone the jmavsim project following the "README" file.  It should be  " https://github.com/PX4/jMAVSim.git " .  A  little mistake ^_^
