### ISSUE TITLE
How to get logs in gazebo and jmavsim simulators

### ISSUE THREAD

**Issue by Sneha-hub115** [PX4/jMAVSim#115]
Hi,
I’m using ubuntu18.04 to build the px4 code for gazebo and jmavsim. I’m stuck with the following issues:

    How to get log files in jmavsim simulator.
    Where i will get logs in jmavsim simulator.
    How to get log files in gazebo simulator.
    Where i will get logs in gazebo simulator.

Thank you.

**Comment by hamishwillee** [comment]
This section is for bugs. For support questions see forums and chat here: http://docs.px4.io/master/en/#support
