### ISSUE TITLE
How to get logs in jMAVSim

### ISSUE THREAD

**Issue by Sneha-hub115** [PX4/jMAVSim#116]
Hi,
I’m using ubuntu 18.04 to build the px4 code for jmavsim using QGround control. I’m stuck with the following issue:

1. How to get logs in jMAVSim simulator?
2. Where do I find logs in jMAVSim simulator?

Thank you

**Comment by hamishwillee** [comment]
Have you considered asking this question on the discussion boards? This isn't a bug.

QGC logs from the simulated vehicle can be got from QGC as usual - e.g. in Documents/QGroundControl/Logs

Logs on the "simulated PX4" are stored in the build tree (irrespective of simulator type)
Firmware/build/px4_sitl_default/logs
