### ISSUE TITLE
How to replay the flight from logs in jMAVSim and gazebo

### ISSUE THREAD

**Issue by Sneha-hub115** [PX4/jMAVSim#117]
Hi,
I'm using ubuntu18.04 to build the px4 code for gazebo and jmavsim. I'm stuck with the following issue:

    1. How to replay the flight from logs in  jMAVSim and gazebo simulators.

Thank you

**Comment by hamishwillee** [comment]
This is documented in the QGC documentation. Please ask support questions in the support forums, not in bug tracker.
