### ISSUE TITLE
Provide keyboard shortcuts to switch the camera view

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/jMAVSim#2]
@molecule Would it be possible to do the view switching here using keyboard shortcuts instead of hardcoding them? Can we print an instruction line on application startup about that?
https://github.com/PX4/jMAVSim/blob/master/src/me/drton/jmavsim/Simulator.java#L122-L140

**Comment by molecule** [comment]
Yes I can add that. So it looks like the options are: FPV, on vehicle with gimbal, and static while pointing to vehicle, is that right? What about a flag -v (for view) and then either fpv, gimbal or static as the options? So the usage string could look like this: java -cp lib/*:out/productionjmavsim.jar me.drton.jmavsim.Simulator -udp <ip address>:14553 -v gimbal

Does that sound good to you?

**Comment by LorenzMeier** [comment]
It sounds good, but keyboard hotkeys would be even better. I think you will often end up wanting to switch views as you fly.

**Comment by DrTon** [comment]
Agree, good idea with hotkeys!

**Comment by LorenzMeier** [comment]
Implemented on master, closing.
