### ISSUE TITLE
Restore serial port functionality

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/jMAVSim#3]
@mcharleb @molecule The serial port functionality in this port seems problematic, I couldn't get normal HIL to work. Is this something you're interested to maintain / have a look or should I add this to my list? I would have a slight preference for our Java guru @molecule to own this part of the project, but I do realize that HIL is out of your area of focus.

**Comment by molecule** [comment]
I think we should maintain previous functionality as much as possible. I'm happy to look into it, but will have to wait until after the big release of my main project (July 17th). In the meantime if you want to document how it's problematic and send me an email that would help with debugging!
