### ISSUE TITLE
Jmavsim Bind failed

### ISSUE THREAD

**Issue by anujkumargupta** [PX4/jMAVSim#40]
Hi i am trying to do the sitl simulation but when i run make posix_sitl_default jmavsim it shows bind failed and its not connecting with QGC 
the complete log is 
anuj@anuj-vm:~/src/Firmware$ make posix_sitl_default jmavsim
PX4 CONFIG: /home/anuj/src/Firmware/build_posix_sitl_default
[  0%] [  1%] Built target prebuild_targets
Built target git_gencpp
[  1%] [  1%] Built target git_genmsg
Built target git_uavcan
[  1%] Built target git_jmavsim
[  2%] [  2%] Built target git_matrix
Built target git_mavlink
[  4%] Built target df_driver_framework
[  4%] [  5%] Built target git_driverframework
Built target xml_gen
[  5%] Built target git_ecl
[  5%] Built target git_gazebo
[  5%] Built target mixer_gen
[ 28%] Built target msg_gen
[ 28%] [ 28%] Built target generate_topic_listener
Built target platforms__common
[ 29%] Built target drivers__boards__sitl
[ 29%] Built target drivers__pwm_out_sim
[ 31%] Built target drivers__device
[ 39%] Built target systemcmds__tests
[ 39%] [ 40%] Built target platforms__posix__drivers__adcsim
Built target platforms__posix__drivers__accelsim
[ 42%] [ 43%] Built target drivers__vmount
Built target drivers__gps
[ 43%] Built target platforms__posix__drivers__barosim
[ 43%] Built target platforms__posix__drivers__airspeedsim
[ 44%] [ 44%] Built target platforms__posix__drivers__gpssim
Built target platforms__posix__drivers__gyrosim
[ 44%] Built target platforms__posix__drivers__ledsim
[ 44%] Built target platforms__posix__drivers__rgbledsim
[ 45%] Built target platforms__posix__drivers__tonealrmsim
[ 46%] Built target platforms__posix__px4_layer
[ 46%] Built target systemcmds__esc_calib
[ 50%] [ 50%] Built target systemcmds__mixer
Built target platforms__posix__work_queue
[ 50%] Built target systemcmds__param
[ 50%] Built target systemcmds__perf
[ 50%] Built target systemcmds__reboot
[ 50%] Built target systemcmds__ver
[ 51%] Built target systemcmds__sd_bench
[ 51%] Built target systemcmds__top
[ 52%] Built target systemcmds__motor_ramp
[ 53%] Built target modules__attitude_estimator_q
[ 54%] Built target systemcmds__topic_listener
[ 54%] Built target modules__dataman
[ 57%] Built target modules__commander
[ 57%] Built target modules__ekf2
[ 57%] Built target lib__external_lgpl
[ 62%] Built target lib__ecl
[ 63%] Built target modules__land_detector
[ 65%] Built target modules__uORB
[ 65%] Built target modules__mc_att_control
[ 67%] Built target modules__mc_pos_control
[ 70%] Built target modules__mavlink
[ 71%] Built target modules__position_estimator_inav
[ 74%] [ 75%] Built target modules__navigator
Built target modules__param
[ 75%] Built target modules__replay
[ 78%] [ 78%] Built target modules__local_position_estimator
[ 79%] Built target modules__sensors
Built target modules__sdlog2
[ 80%] [ 80%] [ 81%] Built target modules__systemlib__mixer
[ 86%] Built target lib__controllib
Built target modules__simulator
Built target modules__systemlib
[ 87%] [ 87%] [ 88%] Built target lib__conversion
Built target lib__DriverFramework__framework
Built target lib__geo
[ 88%] Built target modules__vtol_att_control
[ 88%] [ 88%] [ 89%] Built target lib__mathlib
Built target lib__geo_lookup
Built target lib__launchdetection
[ 90%] Built target lib__mathlib__math__filter
[ 91%] Built target lib__rc
[ 92%] [ 92%] Built target lib__tailsitter_recovery
Built target lib__terrain_estimation
[ 92%] Built target lib__runway_takeoff
[ 92%] Built target examples__px4_simple_app
[ 93%] Built target examples__mc_pos_control_multiplatform
[ 94%] Built target examples__mc_att_control_multiplatform
[ 95%] Built target examples__ekf_att_pos_estimator
[ 95%] Built target examples__attitude_estimator_ekf
[ 95%] [ 96%] Built target lib__rc__rc_tests
Built target drivers__sf0x__sf0x_tests
[ 97%] Built target modules__commander__commander_tests
[ 97%] [ 97%] Built target modules__unit_test
Built target modules__controllib_test
[100%] [ 98%] Built target modules__fw_att_control
Built target modules__uORB__uORB_tests
[100%] [100%] Built target modules__fw_pos_control_l1
Built target modules__logger
[100%] Built target px4
args: /home/anuj/src/Firmware/build_posix_sitl_default/src/firmware/posix/px4 posix-configs/SITL/init/lpe none jmavsim none /home/anuj/src/Firmware /home/anuj/src/Firmware/build_posix_sitl_default
SITL ARGS
sitl_bin: /home/anuj/src/Firmware/build_posix_sitl_default/src/firmware/posix/px4
rcS_dir: posix-configs/SITL/init/lpe
debugger: none
program: jmavsim
model: none
src_path: /home/anuj/src/Firmware
build_path: /home/anuj/src/Firmware/build_posix_sitl_default
empty model, setting iris as default
9772
14117
14812
15607
SITL COMMAND: /home/anuj/src/Firmware/build_posix_sitl_default/src/firmware/posix/px4 /home/anuj/src/Firmware /home/anuj/src/Firmware/posix-configs/SITL/init/lpe/iris
data path: /home/anuj/src/Firmware
commands file: /home/anuj/src/Firmware/posix-configs/SITL/init/lpe/iris

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

18446744073709551605 WARNING: setRealtimeSched failed (not run as root?)
INFO  [dataman] Unkown restart, data manager file 'rootfs/fs/microsd/dataman' size is 103090 bytes
Buildfile: /home/anuj/src/Firmware/Tools/jMAVSim/build.xml

make_dirs:

compile:

create_run_jar:
INFO  [platforms__posix__drivers__ledsim] LED::init
INFO  [platforms__posix__drivers__ledsim] LED::init
WARN  [simulator] bind failed

copy_res:

BUILD SUCCESSFUL
Total time: 0 seconds
Options parsed, starting Sim.
Starting GUI...
3D [dev] 1.6.0-pre12-daily-experimental daily

Thanks

**Comment by bkueng** [comment]
It means it fails to bind to the UDP port. Did you change the default port? Or do you already have something running on UDP port 14560?
