### ISSUE TITLE
fields_updated is always 0 for HIL_SENSOR message

### ISSUE THREAD

**Issue by sytelus** [PX4/jMAVSim#49]
It seems that all HIL_SENSOR sent by jMavSim has fields_updated  set to 0. According to MavLink specs, this should mean that all fields other than linear acceleration should be ignored. Is this correct interpretation and behaviour? If so then gyro fields in HIL_SENSOR should not be having any effect...

**Comment by sytelus** [comment]
Update: @lovettchris looked at the firmware code and found that it simply ignored fields_updated. So we have two issues:

1. jMavSim doesn't set the correct value
2. Firmware ignore all values

**Comment by julianoes** [comment]
Probably outdated, closing.
