### ISSUE TITLE
PID Tuning not working on actual flight 

### ISSUE THREAD

**Issue by salim616** [PX4/jMAVSim#54]
Hi everyone , 

@AndreasAntener I am new to programming. I have managed to tune my bespoke quad on JmavSim using a step input . all works fine on the simulation. when I transferred PID parameters into the Pixhawk. the quad started behaving weirdly and didnt even managed to takeoff . any help would be appreciated 

video link: https://www.dropbox.com/s/chxxrwyg2n9kuug/video-1487278360.mp4?dl=0

**Comment by kd0aij** [comment]
Did you calibrate your ESCs?
Also filing an issue is not an appropriate way to request support. You should post newbie questions on one of the support forums.
