### ISSUE TITLE
jMAVSim without GUI

### ISSUE THREAD

**Issue by GregoireH** [PX4/jMAVSim#59]
Hello,

Thanks to this post: http://discuss.px4.io/t/lightweight-or-command-line-sitl-simulation-options/2285
Modifying Visualizer3D.java3, and change setVisible(true) to 
setVisible(false).

I could run SITL using jMAVSim without the GUI as my low computational power computer was having troubles running it properly.

Do you know if most of PX4 users are using the graphics ?
Or if most of us are just wasting CPU with jMAVSim fency graphics...

I was wondering if we could set a parameter for this in order to be able to specify that we want to turn off graphics, without having to edit and compile jMAVSim .
Do you think it could be feasible and that some people could benefit from that ?

looking forward hearing from you.
Best

**Comment by julianoes** [comment]
Hi, thanks for the note. I think this would be worthwhile to add. Possibly it should be consistent with the `HEADLESS=1` mode that you can use for the Gazebo simulation.

**Comment by julianoes** [comment]
This would still be nice, someday. FYI @JonasVautherin.

**Comment by JonasVautherin** [comment]
If I remember correctly, I tried that a few months ago. But the fix proposed here was only disabling the graphics rendering and not making it truly headless (somehow it still needed an X server to be running, so I could not run that, say, in a headless docker).

**Comment by ekatzfey** [comment]
Did this ever get resolved? I would really like to be able to run this in a headless docker.

Thanks!

**Comment by hamishwillee** [comment]
@ekatzfey No, it did not. We'd happily accept a PR! 

Note, FWIW
-  you can run _Gazebo_ headless: http://dev.px4.io/master/en/simulation/gazebo.html#headless-mode
- With [lockstep](http://dev.px4.io/master/en/simulation/#lockstep-simulation) now supported the simulation may still run fairly "heavy" but it is much more reliable on low performance hardware.

**Comment by katzfey** [comment]
I submitted a PR.
