### ISSUE TITLE
Not compatible with PX4 v1.7.3

### ISSUE THREAD

**Issue by kalnal2506** [PX4/jMAVSim#68]
I tried HITL with PX4 v1.7.3 stable which flashed on my Pixhawk2.
But I can't take off or control due to consist MANUAL CONTROL LOST, REGAIN warning.
please help me about this. Is it fixing or new bug?
Regards.

**Comment by julianoes** [comment]
@kalnal2506 is this still an issue?

**Comment by julianoes** [comment]
Closing, please re-open if this is still an issue.
