### ISSUE TITLE
Yuneec 520: HITL simulator keep crashing into land after takeoff

### ISSUE THREAD

**Issue by Anhtastic** [PX4/jMAVSim#93]
HITL simulator would work but after taking off it immediately crash into land. It start wobbling as soon as it take off and then crash into land. 

I'm following instructions from here: https://developer.yuneec.com/documentation/121/HITL-Testing-for-Mac

I've made sure the QGC HITL is enabled and closing it before running the simulator.

I'm currently using:
 java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

Greatly appreciated if someone can help me figure out why the Yuneec 520 drone simulator keeps on crashing after taking off.

**Comment by hamishwillee** [comment]
@julianoes FYI - any ideas who might be able to chase this one up?

**Comment by julianoes** [comment]
Thanks @hamishwillee.

@potaito @simonegu I can try to reproduce this for now.

**Comment by potaito** [comment]
I was unable to use H520 HITL as well after updating to the newest commit. Last known working commit for me is cb2d13087a671d80a68e65109ff4da307022dea0, and the broken commit is 00bdf6d92b6a8678f5b683a3ebca9e52e88cb5ce. I have not yet found the time to look into this :/ There are two dozen commit in between and it should be possible to pin-point when exactly H520 HITL broke.

**Comment by julianoes** [comment]
Right, so I must have broken it with the lockstep changes. I'll check.

**Comment by potaito** [comment]
Thank you very much

**Comment by julianoes** [comment]
I think I've fixed it. Would be cool if you could also test: #94 .

**Comment by potaito** [comment]
Tested and confirmed to be working :+1:

**Comment by Anhtastic** [comment]
Sorry guys, it was President's day yesterday so no working day, but I have tested this morning and it worked. Thank you so much! 👍
